apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-login
spec:
  selector:
    matchLabels:
      app: node-login
  template:
    metadata:
      labels:
        app: node-login
    spec:
      containers:
        - name: node-login
          image: mandarr/node-login:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: node-login
spec:
  type: LoadBalancer
  selector:
    app: node-login
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 31110
